import { FaBook, FaClock, FaHistory, FaCalendarAlt } from "react-icons/fa";
export const grammarTopics = [
    {
        id: 1,
        title: "Present Simple",
        description: "Used for habits, routines, facts, and general truths",
        examples: [
            "I go to work every day.",
            "Water boils at 100 degrees Celsius.",
            "She lives in New York.",
        ],
        rules: [
            "Use base form for I/you/we/they (e.g., I play)",
            "Add -s/-es for he/she/it (e.g., He plays)",
            "Negative: subject + don't/doesn't + base form",
            "Question: Do/Does + subject + base form?",
        ],
        timeSignals: [
            "always",
            "usually",
            "often",
            "sometimes",
            "never",
            "every day",
            "once a week",
        ],
        icon: FaBook,
        completed: false,
    },
    {
        id: 2,
        title: "Present Continuous",
        description: "Used for actions happening now or around now",
        examples: [
            "I am studying English right now.",
            "They are playing football this afternoon.",
            "She is cooking dinner at the moment.",
        ],
        rules: [
            "Form: subject + am/is/are + verb-ing",
            "Negative: subject + am/is/are + not + verb-ing",
            "Question: Am/Is/Are + subject + verb-ing?",
        ],
        timeSignals: [
            "now",
            "at the moment",
            "currently",
            "these days",
            "nowadays",
            "Look!",
            "Listen!",
        ],
        icon: FaClock,
        completed: false,
    },
    {
        id: 3,
        title: "Present Perfect",
        description: "Used for past actions with a connection to the present",
        examples: [
            "I have visited Paris three times.",
            "She has lived in London for two years.",
            "They have not finished their homework yet.",
        ],
        rules: [
            "Form: subject + have/has + past participle",
            "Negative: subject + have/has + not + past participle",
            "Question: Have/Has + subject + past participle?",
        ],
        timeSignals: [
            "already",
            "yet",
            "just",
            "ever",
            "never",
            "for",
            "since",
            "so far",
            "recently",
        ],
        icon: FaHistory,
        completed: false,
    },
    {
        id: 4,
        title: "Present Perfect Continuous",
        description:
            "Used for ongoing actions that started in the past and continue to the present",
        examples: [
            "I have been waiting for an hour.",
            "She has been studying English since 2020.",
            "They have been playing football.",
        ],
        rules: [
            "Form: subject + have/has + been + verb-ing",
            "Negative: subject + have/has + not + been + verb-ing",
            "Question: Have/Has + subject + been + verb-ing?",
        ],
        timeSignals: [
            "for",
            "since",
            "all day",
            "recently",
            "lately",
            "how long",
        ],
        icon: FaClock,
        completed: false,
    },
    {
        id: 5,
        title: "Past Simple",
        description: "Used for completed actions in the past",
        examples: [
            "I visited Paris last summer.",
            "She went to the store yesterday.",
            "They didn't come to the party.",
        ],
        rules: [
            "Regular verbs: add -ed (e.g., played)",
            "Irregular verbs: use past form (e.g., went, saw)",
            "Negative: subject + didn't + base form",
            "Question: Did + subject + base form?",
        ],
        timeSignals: [
            "yesterday",
            "last week",
            "last month",
            "last year",
            "ago",
            "in 2010",
            "when?",
        ],
        icon: FaHistory,
        completed: false,
    },
    {
        id: 6,
        title: "Past Continuous",
        description:
            "Used for actions that were in progress at a specific time in the past",
        examples: [
            "I was studying when she called.",
            "They were playing tennis at 5 PM yesterday.",
            "What were you doing at midnight?",
        ],
        rules: [
            "Form: subject + was/were + verb-ing",
            "Negative: subject + was/were + not + verb-ing",
            "Question: Was/Were + subject + verb-ing?",
        ],
        timeSignals: [
            "at this time yesterday",
            "while",
            "when",
            "as",
            "at that moment",
        ],
        icon: FaClock,
        completed: false,
    },
    {
        id: 7,
        title: "Past Perfect",
        description:
            "Used for actions completed before another action in the past",
        examples: [
            "I had finished dinner before she arrived.",
            "They had left when I got there.",
            "She hadn't studied before the exam.",
        ],
        rules: [
            "Form: subject + had + past participle",
            "Negative: subject + had + not + past participle",
            "Question: Had + subject + past participle?",
        ],
        timeSignals: [
            "before",
            "after",
            "already",
            "just",
            "by the time",
            "when",
            "never",
        ],
        icon: FaHistory,
        completed: false,
    },
    {
        id: 8,
        title: "Past Perfect Continuous",
        description:
            "Used for ongoing actions that were happening before another action in the past",
        examples: [
            "I had been studying for three hours before I took a break.",
            "They had been waiting for an hour when the bus finally arrived.",
            "She had not been feeling well before she went to the doctor.",
        ],
        rules: [
            "Form: subject + had been + verb-ing",
            "Negative: subject + had + not + been + verb-ing",
            "Question: Had + subject + been + verb-ing?",
        ],
        timeSignals: ["for", "since", "before", "until then", "by the time"],
        icon: FaClock,
        completed: false,
    },
    {
        id: 9,
        title: "Future Simple",
        description:
            "Used for future actions, predictions, promises, and spontaneous decisions",
        examples: [
            "I will call you tomorrow.",
            "It will rain next week.",
            "I'll help you with that.",
        ],
        rules: [
            "Form: subject + will + base form",
            "Negative: subject + will + not + base form",
            "Question: Will + subject + base form?",
        ],
        timeSignals: [
            "tomorrow",
            "next week",
            "next month",
            "next year",
            "in the future",
            "soon",
        ],
        icon: FaCalendarAlt,
        completed: false,
    },
    {
        id: 10,
        title: "Future Continuous",
        description:
            "Used for actions that will be in progress at a specific time in the future",
        examples: [
            "I will be studying at 8 PM tomorrow.",
            "This time next week, they will be traveling to Paris.",
            "Will you be working late tomorrow?",
        ],
        rules: [
            "Form: subject + will + be + verb-ing",
            "Negative: subject + will + not + be + verb-ing",
            "Question: Will + subject + be + verb-ing?",
        ],
        timeSignals: [
            "at this time tomorrow",
            "at that moment",
            "all day tomorrow",
            "while",
        ],
        icon: FaClock,
        completed: false,
    },
    {
        id: 11,
        title: "Future Perfect",
        description:
            "Used for actions that will be completed before another action in the future",
        examples: [
            "I will have finished my homework by 8 PM.",
            "By next year, she will have graduated from university.",
            "Will you have completed the project by the deadline?",
        ],
        rules: [
            "Form: subject + will + have + past participle",
            "Negative: subject + will + not + have + past participle",
            "Question: Will + subject + have + past participle?",
        ],
        timeSignals: ["by", "by the time", "before", "by then", "by next week"],
        icon: FaHistory,
        completed: false,
    },
    {
        id: 12,
        title: "Future Perfect Continuous",
        description:
            "Used for ongoing actions that will continue up until a point in the future",
        examples: [
            "By next month, I will have been studying English for five years.",
            "By the time we arrive, they will have been waiting for two hours.",
            "How long will you have been working here by next year?",
        ],
        rules: [
            "Form: subject + will + have + been + verb-ing",
            "Negative: subject + will + not + have + been + verb-ing",
            "Question: Will + subject + have + been + verb-ing?",
        ],
        timeSignals: ["by", "for", "by the time", "next year"],
        icon: FaClock,
        completed: false,
    },
];
